baseURL = 'https://iamanshik.online/'
languageCode = 'en-us'
title = 'Anshik Singh'
theme = 'typo'

# Google analytics code
# googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "Anshik's Tech Blog"

# Appearance settings
theme = 'light'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
# homeIntroTitle = 'Hi!'
homeIntroContent = """
I am [Anshik Singh](/cv), a Software Engineer Intern at [SilverPush](https://www.silverpush.co/), currently based in India.  
My interests span across **web development**, **blockchain**, and **system design**.  

To contact me directly, send an email to:  
*[anshikthind at gmail dot com](mailto:anshikthind@gmail.com)*
"""

footerContent = """
`make build all` //[source](https://github.com/anshiq/profile)

---

Powered by [Hugo](https://gohugo.io/) · Theme: [tomfran/typo](https://github.com/tomfran/typo)
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'blogs'
summaryLength = 150
homeCollectionLimit = 4
listSummaries = true

# Lists parameters
paginationSize = 100
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"


# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"
[[params.menu]]
name = "notes"
url = "/notebook"


[[params.menu]]
name = "CV"
url = "/cv"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
