[[redirects]]
from = "https://ts-notebook.iamanshik.online/*"
to = "/notebooks/ts/:splat"
status = 200
force = true

[[redirects]]
from = "https://golang-notebook.iamanshik.online/*"
to = "/notebooks/golang/:splat"
status = 200
force = true
# profile
[[redirects]]
from = "https://iamanshik.online/*"
to = "/profile/:splat"
status = 200
force = true
