[[redirects]]
  from = "https://ts-notebook.iamanshik.online/*"
  to = "/ts/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://golang-notebook.iamanshik.online/*"
  to = "/golang/:splat"
  status = 200
  force = true

